import Link from "next/link";
import { redirect } from "next/navigation";
import { connection } from "next/server";
import { Users, ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { inviteTeamMember, setTeamUserActive, setTeamUserRole } from "./actions";

const ROLES = ["ADMIN", "SALES", "AGENT"] as const;
type Member = { id: string; email: string; full_name: string | null; role: string; platform_role: string; is_active: boolean; created_at: string; onboarding_completed: boolean };

export default async function TeamPage() {
  await connection();
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/auth/login");
  const { data: members, error } = await supabase.rpc("get_workspace_team");
  if (error) redirect("/protected");
  return <main className="leadflow-page min-h-screen px-4 sm:px-6 lg:px-10"><div className="mx-auto max-w-[1200px] py-6 sm:py-8">
    <Link prefetch={false} href="/protected" className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.16em] text-white/35 hover:text-[#b7ff58]"><ArrowLeft size={13}/> Back to workspace</Link>
    <header className="mt-7 flex flex-col gap-5 border-b border-white/10 pb-8 md:flex-row md:items-end md:justify-between"><div><p className="leadflow-kicker">WORKSPACE / PEOPLE</p><h1 className="mt-3 text-5xl font-black uppercase tracking-[-.06em] sm:text-7xl">Team</h1><p className="mt-4 max-w-xl text-sm leading-6 text-white/40">Invite teammates and control workspace access.</p></div><div className="border border-[#b7ff58]/20 bg-[#b7ff58]/[.04] px-4 py-3 text-[9px] font-bold uppercase tracking-[.14em] text-[#b7ff58]"><ShieldCheck size={13} className="mr-2 inline"/>Owner / Admin control</div></header>
    <section className="mt-8 grid gap-8 lg:grid-cols-[.8fr_1.2fr]">
      <section className="border border-white/10 bg-[#080808] p-5 sm:p-6"><p className="leadflow-kicker">INVITE</p><h2 className="mt-2 text-2xl font-black uppercase tracking-[-.04em]">Add a teammate</h2><p className="mt-2 text-xs leading-5 text-white/30">They'll receive a secure Supabase invitation and set their own password.</p><form action={inviteTeamMember} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-[9px] font-bold uppercase tracking-[.14em] text-white/30">Full name</span><input required name="full_name" className="w-full border border-white/10 bg-black px-3 py-3 text-sm outline-none focus:border-[#b7ff58]/30" placeholder="Rahul Sharma"/></label><label className="block"><span className="mb-2 block text-[9px] font-bold uppercase tracking-[.14em] text-white/30">Email</span><input required type="email" name="email" className="w-full border border-white/10 bg-black px-3 py-3 text-sm outline-none focus:border-[#b7ff58]/30" placeholder="rahul@company.com"/></label><label className="block"><span className="mb-2 block text-[9px] font-bold uppercase tracking-[.14em] text-white/30">Role</span><select name="role" defaultValue="SALES" className="w-full border border-white/10 bg-black px-3 py-3 text-sm uppercase outline-none focus:border-[#b7ff58]/30">{ROLES.map(r=><option key={r}>{r}</option>)}</select></label><button type="submit" className="leadflow-button leadflow-button-primary w-full justify-center">Send invitation <Mail size={13}/></button></form></section>
      <section className="border border-white/10 bg-[#080808]"><div className="border-b border-white/10 p-5 sm:p-6"><p className="leadflow-kicker">MEMBERS</p><h2 className="mt-2 text-2xl font-black uppercase tracking-[-.04em]">Your team</h2></div><div>{(members as Member[]).map(member=>{const protectedUser=member.platform_role==='SUPER_ADMIN'; const owner=member.role==='OWNER'; return <div key={member.id} className="border-b border-white/[.06] p-5 last:border-0"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="font-semibold text-white/85">{member.full_name||"Unnamed user"}</p><p className="mt-1 flex items-center gap-2 truncate text-xs text-white/30"><Mail size={12}/>{member.email}</p></div><span className={`shrink-0 border px-2 py-1 text-[8px] font-bold uppercase tracking-[.14em] ${owner?'border-[#b7ff58]/20 text-[#b7ff58]':'border-white/10 text-white/45'}`}>{member.role}</span></div><div className="mt-3 text-[9px] font-bold uppercase tracking-[.12em] text-white/25">{member.is_active?'Active':'Inactive'} · {member.onboarding_completed?'Onboarded':'Pending onboarding'}</div>{!protectedUser&&!owner&&<div className="mt-4 flex flex-col gap-3 sm:flex-row"><form action={setTeamUserRole.bind(null, member.id)} className="flex flex-1 gap-2"><select name="role" defaultValue={member.role} className="min-w-0 flex-1 border border-white/10 bg-black px-3 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-white/70">{ROLES.map(r=><option key={r}>{r}</option>)}</select><button className="border border-white/10 px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] text-white/50 hover:border-[#b7ff58]/30 hover:text-[#b7ff58]">Save</button></form><form action={setTeamUserActive.bind(null, member.id, !member.is_active)}><button className={`border px-3 py-2 text-[9px] font-black uppercase tracking-[.12em] ${member.is_active?'border-red-400/15 text-red-300/60':'border-[#b7ff58]/20 text-[#b7ff58]'}`}>{member.is_active?'Deactivate':'Activate'}</button></form></div>}</div>})}{!(members as Member[]).length&&<div className="p-8 text-center text-xs text-white/30"><Users size={22} className="mx-auto mb-3"/>No team members yet.</div>}</div></section>
    </section>
  </div></main>;
}
