"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { Activity, ArrowUpRight, Bot, CheckCircle2, Clock3, Mail, MessageSquare, PauseCircle, PlayCircle, PlugZap, Search, Sparkles, Target, UserRound, UsersRound, Zap } from "lucide-react";

type CustomerRow = { id: string; name: string; email: string | null; phone: string | null; source: string | null; lastSeen: string };
type ConversationRow = { id: string; customerId: string; name: string; channel: string; status: string; aiPaused: boolean; lastMessage: string | null; updated: string };
type MessageRow = { id: string; conversationId: string; direction: string; actor: string; body: string | null; createdAt: string };
type TaskRow = { id: string; name: string; channel: string; state: string; scheduledAt: string; reason: string | null; message: string | null };
type CampaignRow = { name: string; leads: number; hot: number; qualified: number; value: number };
type AgentRow = { name: string; job: string; workflow: string; runs: number; failures: number; active: boolean; description: string };
type IntegrationRow = { component: string; healthy: boolean; issueCount: number; checkedAt: string };

type Props =
  | { kind: "customers"; customers: CustomerRow[] }
  | { kind: "conversations"; conversations: ConversationRow[]; messages: MessageRow[] }
  | { kind: "tasks"; tasks: TaskRow[] }
  | { kind: "ai-agents"; agents: AgentRow[] }
  | { kind: "campaigns"; campaigns: CampaignRow[] }
  | { kind: "analytics"; leads: { source: string | null; score: number; value: number; stage: string; temperature: string | null; createdAt: string }[] }
  | { kind: "integrations"; integrations: IntegrationRow[] };

export function WorkspaceModule(props: Props) {
  if (props.kind === "customers") return <Customers customers={props.customers} />;
  if (props.kind === "conversations") return <Conversations conversations={props.conversations} messages={props.messages} />;
  if (props.kind === "tasks") return <Tasks tasks={props.tasks} />;
  if (props.kind === "ai-agents") return <Agents agents={props.agents} />;
  if (props.kind === "campaigns") return <Campaigns campaigns={props.campaigns} />;
  if (props.kind === "analytics") return <Analytics leads={props.leads} />;
  return <Integrations integrations={props.integrations} />;
}

function Customers({ customers }: { customers: CustomerRow[] }) {
  const [query, setQuery] = useState("");
  const filtered = customers.filter((c) => `${c.name} ${c.email || ""} ${c.phone || ""}`.toLowerCase().includes(query.toLowerCase()));
  return <><Stats items={[["ACTIVE CUSTOMERS", customers.length, "Live customer records"], ["WITH EMAIL", customers.filter((c) => c.email).length, "Reachable contacts"], ["SOURCES", new Set(customers.map((c) => c.source).filter(Boolean)).size, "Acquisition sources"]]} /><section className="mt-8 border border-white/10 bg-[#080808]"><Toolbar placeholder="Search customers..." value={query} onChange={setQuery} /><div className="divide-y divide-white/[.08]">{filtered.map((c) => <div key={c.id} className="grid gap-4 p-5 transition hover:bg-white/[.025] md:grid-cols-[1.2fr_1fr_.7fr_.7fr] md:items-center"><div><p className="font-semibold text-white/85">{c.name}</p><p className="mt-1 text-[10px] text-white/30">{c.email || c.phone || "No contact details"}</p></div><p className="text-xs text-white/40">{c.source || "Unknown source"}</p><p className="text-[10px] uppercase tracking-[.15em] text-white/25">Last seen<br/><span className="text-white/50">{formatDate(c.lastSeen)}</span></p><Link href={`/leads?customer=${c.id}`} className="leadflow-button justify-self-start md:justify-self-end">Open context <ArrowUpRight size={12}/></Link></div>)}{!filtered.length && <Empty title="No customers match" text="New customer records will appear here when enquiries arrive." />}</div></section></>;
}

function Conversations({ conversations, messages }: { conversations: ConversationRow[]; messages: MessageRow[] }) {
  const [selected, setSelected] = useState(conversations[0]?.id || null);
  const active = conversations.find((c) => c.id === selected) || conversations[0];
  const activeMessages = messages.filter((m) => m.conversationId === active?.id);
  return <div className="grid min-h-[620px] border border-white/10 bg-[#080808] lg:grid-cols-[320px_1fr]"><div className="border-b border-white/10 lg:border-b-0 lg:border-r"><div className="border-b border-white/10 p-5"><p className="leadflow-kicker">LIVE INBOX</p><h3 className="mt-2 text-xl font-black uppercase">Conversations</h3></div><div className="divide-y divide-white/[.07]">{conversations.map((c) => <button key={c.id} onClick={() => setSelected(c.id)} className={`w-full p-4 text-left transition ${selected === c.id ? "bg-[#b7ff58]/[.07]" : "hover:bg-white/[.025]"}`}><div className="flex items-center justify-between gap-3"><span className="truncate text-xs font-semibold text-white/80">{c.name}</span><span className="text-[9px] uppercase tracking-wider text-white/25">{c.channel}</span></div><p className="mt-2 line-clamp-1 text-[10px] text-white/30">{c.lastMessage || "No messages yet"}</p><div className="mt-2 flex items-center gap-2 text-[9px] text-white/25"><span className={c.aiPaused ? "text-amber-300" : "text-[#b7ff58]"}>{c.aiPaused ? "AI paused" : "AI active"}</span><span>·</span><span>{c.status}</span></div></button>)}{!conversations.length && <Empty title="Inbox is empty" text="Conversations will appear when your connected channels receive messages." />}</div></div><div className="flex min-w-0 flex-col">{active ? <><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-lg font-black">{active.name}</p><p className="mt-1 text-[10px] uppercase tracking-[.15em] text-white/25">{active.channel} · {active.status}</p></div><span className="border border-[#b7ff58]/25 bg-[#b7ff58]/[.05] px-3 py-2 text-[9px] font-bold uppercase tracking-[.15em] text-[#b7ff58]">{active.aiPaused ? "Human control" : "AI handling"}</span></div><div className="flex-1 space-y-4 overflow-auto p-5 sm:p-8">{activeMessages.map((m) => <div key={m.id} className={`max-w-[78%] ${m.direction === "inbound" ? "" : "ml-auto"}`}><div className={`border p-4 ${m.direction === "inbound" ? "border-white/10 bg-[#050505]" : "border-[#b7ff58]/20 bg-[#b7ff58]/[.06]"}`}><p className="whitespace-pre-wrap text-sm leading-6 text-white/75">{m.body || "(empty message)"}</p></div><p className="mt-1 text-[9px] uppercase tracking-[.12em] text-white/20">{m.actor} · {formatDate(m.createdAt)}</p></div>)}{!activeMessages.length && <div className="flex h-full min-h-[300px] items-center justify-center text-xs text-white/25">No messages recorded for this conversation.</div>}</div><div className="border-t border-white/10 p-4"><div className="flex items-center gap-3 border border-white/10 p-3"><MessageSquare size={14} className="text-white/25"/><span className="text-xs text-white/25">Reply composer will use the connected channel here.</span></div></div></> : <Empty title="Select a conversation" text="Choose a customer conversation from the inbox." />}</div></div>;
}

function Tasks({ tasks }: { tasks: TaskRow[] }) {
  const [filter, setFilter] = useState("ALL");
  const filtered = tasks.filter((t) => filter === "ALL" || t.state.toUpperCase() === filter);
  return <><Stats items={[["DUE", tasks.filter((t) => new Date(t.scheduledAt).getTime() <= Date.now()).length, "Scheduled for now or earlier"], ["QUEUED", tasks.filter((t) => t.state.toUpperCase() === "QUEUED").length, "Waiting for execution"], ["SENT", tasks.filter((t) => t.state.toUpperCase() === "SENT").length, "Completed follow-ups"]]} /><section className="mt-8 border border-white/10 bg-[#080808]"><div className="flex flex-wrap gap-1 border-b border-white/10 p-4">{["ALL", "QUEUED", "SENT", "FAILED", "CANCELED"].map((f) => <button key={f} onClick={() => setFilter(f)} className={`px-3 py-2 text-[9px] font-bold uppercase tracking-[.14em] ${filter === f ? "bg-[#b7ff58]/10 text-[#b7ff58]" : "text-white/30"}`}>{f}</button>)}</div><div className="divide-y divide-white/[.07]">{filtered.map((t) => <div key={t.id} className="grid gap-4 p-5 md:grid-cols-[1.1fr_.7fr_.8fr_1.5fr] md:items-center"><div><p className="font-semibold text-white/80">{t.name}</p><p className="mt-1 text-[10px] text-white/30">{t.channel}</p></div><Status state={t.state}/><p className="text-xs text-white/40">{formatDate(t.scheduledAt)}</p><p className="text-xs leading-5 text-white/35">{t.reason || t.message || "No task reason recorded."}</p></div>)}{!filtered.length && <Empty title="No follow-ups here" text="LeadFlow will surface scheduled follow-ups when the automation layer creates them." />}</div></section></>;
}

function Agents({ agents }: { agents: AgentRow[] }) {
  return <><div className="border border-white/10 bg-[#080808] p-6 sm:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="leadflow-kicker">YOUR AI TEAM</p><h3 className="mt-2 max-w-3xl text-3xl font-black uppercase leading-none tracking-[-.05em] sm:text-5xl">Specialists, not a magic button.</h3><p className="mt-4 max-w-2xl text-sm leading-6 text-white/40">Each agent has one job. LeadFlow can show what ran, what failed and where a human needs to take over.</p></div><Link href="/integrations" className="leadflow-button">Connect systems <PlugZap size={13}/></Link></div></div><div className="mt-5 grid gap-px border border-white/10 bg-white/10 md:grid-cols-2 xl:grid-cols-3">{agents.map((agent) => <div key={agent.name} className="bg-[#080808] p-6"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center bg-[#b7ff58]/10 text-[#b7ff58]"><Bot size={18}/></div><span className={`flex items-center gap-1 text-[9px] font-bold uppercase tracking-[.15em] ${agent.active ? "text-[#b7ff58]" : "text-white/25"}`}>{agent.active ? <CheckCircle2 size={12}/> : <PauseCircle size={12}/>} {agent.active ? "Active" : "Idle"}</span></div><p className="mt-7 text-xl font-black uppercase tracking-[-.03em]">{agent.name}</p><p className="mt-1 text-xs font-semibold text-[#b7ff58]">{agent.job}</p><p className="mt-4 min-h-10 text-xs leading-5 text-white/35">{agent.description}</p><div className="mt-6 grid grid-cols-2 gap-px border border-white/10 bg-white/10"><div className="bg-[#050505] p-3"><p className="text-[9px] uppercase tracking-wider text-white/25">Runs</p><p className="mt-1 text-lg font-black">{agent.runs}</p></div><div className="bg-[#050505] p-3"><p className="text-[9px] uppercase tracking-wider text-white/25">Failures</p><p className="mt-1 text-lg font-black text-red-300">{agent.failures}</p></div></div><div className="mt-4 flex items-center justify-between text-[9px] uppercase tracking-[.15em] text-white/20"><span>{agent.workflow}</span><Activity size={12}/></div></div>)}</div></>;
}

function Campaigns({ campaigns }: { campaigns: CampaignRow[] }) {
  return <><Stats items={[["CAMPAIGNS", campaigns.length, "Detected from live lead attribution"], ["LEADS", campaigns.reduce((n, c) => n + c.leads, 0), "Attributed records"], ["VALUE", formatCurrency(campaigns.reduce((n, c) => n + c.value, 0)), "Pipeline value"]]} /><div className="mt-8 grid gap-4 md:grid-cols-2">{campaigns.map((c) => <article key={c.name} className="border border-white/10 bg-[#080808] p-6"><div className="flex items-start justify-between gap-4"><div><p className="leadflow-kicker">CAMPAIGN SIGNAL</p><h3 className="mt-2 text-2xl font-black uppercase tracking-[-.04em]">{c.name}</h3></div><Sparkles size={18} className="text-[#b7ff58]"/></div><div className="mt-7 grid grid-cols-2 gap-px border border-white/10 bg-white/10 sm:grid-cols-4"><SmallStat label="LEADS" value={c.leads}/><SmallStat label="HOT" value={c.hot}/><SmallStat label="QUALIFIED" value={c.qualified}/><SmallStat label="VALUE" value={formatCurrency(c.value)}/></div><div className="mt-5 flex items-center gap-2 text-[10px] text-white/30"><Zap size={12} className="text-[#b7ff58]"/> Campaign performance is derived from lead attribution.</div></article>)}{!campaigns.length && <div className="border border-white/10 bg-[#080808] p-12 text-center md:col-span-2"><Target size={22} className="mx-auto text-white/20"/><h3 className="mt-4 font-black uppercase">No campaign data yet</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-white/30">Once leads carry a campaign or UTM source, LeadFlow can turn them into a measurable demand view.</p></div>}</div></>;
}

function Analytics({ leads }: { leads: { source: string | null; score: number; value: number; stage: string; temperature: string | null; createdAt: string }[] }) {
  const total = leads.length; const hot = leads.filter((l) => String(l.temperature).toUpperCase() === "HOT").length; const qualified = leads.filter((l) => ["QUALIFIED", "PROPOSAL", "WON"].includes(l.stage.toUpperCase())).length; const won = leads.filter((l) => l.stage.toUpperCase() === "WON").length; const value = leads.reduce((n, l) => n + l.value, 0); const avg = total ? Math.round(leads.reduce((n, l) => n + l.score, 0) / total) : 0; const sources = Object.entries(leads.reduce<Record<string, number>>((a, l) => { const k = l.source || "Other"; a[k] = (a[k] || 0) + 1; return a; }, {})).sort((a,b) => b[1]-a[1]).slice(0, 6); const max = Math.max(...sources.map(([,n])=>n),1);
  return <><div className="grid gap-px border border-white/10 bg-white/10 sm:grid-cols-2 xl:grid-cols-4"><Metric label="LEADS" value={total} detail="Live records"/><Metric label="AVG SCORE" value={avg} detail="AI qualification"/><Metric label="QUALIFIED" value={qualified} detail={`${percent(qualified,total)}% of leads`}/><Metric label="PIPELINE" value={formatCurrency(value)} detail={`${won} won records`}/></div><div className="mt-8 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><section className="border border-white/10 bg-[#080808] p-6"><p className="leadflow-kicker">CONVERSION FLOW</p><h3 className="mt-2 text-2xl font-black uppercase">From enquiry to revenue</h3><div className="mt-8 space-y-5"><Funnel label="Captured" value={total} total={total}/><Funnel label="Hot" value={hot} total={total}/><Funnel label="Qualified" value={qualified} total={total}/><Funnel label="Won" value={won} total={total}/></div></section><section className="border border-white/10 bg-[#080808] p-6"><p className="leadflow-kicker">SOURCE PERFORMANCE</p><h3 className="mt-2 text-2xl font-black uppercase">Demand by source</h3><div className="mt-8 space-y-5">{sources.map(([source,count])=><div key={source}><div className="mb-2 flex justify-between text-xs"><span className="text-white/50">{source}</span><span className="font-bold">{count}</span></div><div className="h-1 bg-white/10"><div className="h-full customer-gradient" style={{width:`${Math.round(count/max*100)}%`}}/></div></div>)}{!sources.length&&<p className="text-xs text-white/25">No source data yet.</p>}</div></section></div></>;
}

function Integrations({ integrations }: { integrations: IntegrationRow[] }) {
  return <><div className="border border-white/10 bg-[#080808] p-6 sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="leadflow-kicker">CONNECTED SYSTEMS</p><h3 className="mt-2 text-3xl font-black uppercase tracking-[-.05em]">Your automation surface.</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-white/35">Only show integrations as connected when LeadFlow can verify their health. No fake green checkmarks.</p></div><Link href="/contact" className="leadflow-button leadflow-button-primary">Request integration <ArrowUpRight size={13}/></Link></div></div><div className="mt-6 grid gap-px border border-white/10 bg-white/10 md:grid-cols-2">{integrations.map((i)=><div key={i.component} className="bg-[#080808] p-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center border border-white/10"><PlugZap size={17} className={i.healthy ? "text-[#b7ff58]" : "text-white/30"}/></div><div><p className="font-semibold">{i.component}</p><p className="mt-1 text-[9px] uppercase tracking-[.15em] text-white/25">Checked {formatDate(i.checkedAt)}</p></div></div><span className={`text-[9px] font-bold uppercase tracking-[.15em] ${i.healthy ? "text-[#b7ff58]" : "text-amber-300"}`}>{i.healthy ? "Healthy" : `${i.issueCount} issue${i.issueCount === 1 ? "" : "s"}`}</span></div></div>)}{!integrations.length&&<div className="bg-[#080808] p-12 text-center md:col-span-2"><PlugZap size={24} className="mx-auto text-white/20"/><h3 className="mt-4 text-xl font-black uppercase">No health checks recorded</h3><p className="mx-auto mt-2 max-w-lg text-xs leading-5 text-white/30">LeadFlow will not pretend a provider is connected. Connect a source and the health monitor can report its actual state here.</p></div>}</div></>;
}

function Stats({ items }: { items: [string, string | number, string][] }) { return <div className="grid gap-px border border-white/10 bg-white/10 sm:grid-cols-3">{items.map(([label,value,detail])=><div key={label} className="bg-[#080808] p-5"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-white/30">{label}</p><p className="mt-3 text-3xl font-black tracking-[-.04em]">{value}</p><p className="mt-1 text-[10px] text-white/30">{detail}</p></div>)}</div>; }
function Toolbar({ placeholder, value, onChange }: { placeholder: string; value: string; onChange: (v:string)=>void }) { return <div className="flex items-center gap-2 border-b border-white/10 p-4"><Search size={14} className="text-white/30"/><input value={value} onChange={(e)=>onChange(e.target.value)} placeholder={placeholder} className="w-full bg-transparent text-xs outline-none placeholder:text-white/25"/></div>; }
function Status({ state }: { state: string }) { const s = state.toUpperCase(); return <span className={`inline-flex w-fit items-center gap-1 border px-2 py-1 text-[8px] font-bold uppercase tracking-[.12em] ${s === "SENT" ? "border-[#b7ff58]/25 text-[#b7ff58]" : s === "FAILED" ? "border-red-300/25 text-red-300" : "border-white/10 text-white/35"}`}>{s === "SENT" ? <CheckCircle2 size={10}/> : <Clock3 size={10}/>} {s}</span>; }
function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <div className="bg-[#080808] p-5"><p className="text-[9px] font-bold uppercase tracking-[.18em] text-white/30">{label}</p><p className="mt-3 text-3xl font-black tracking-[-.04em]">{value}</p><p className="mt-1 text-[10px] text-white/30">{detail}</p></div>; }
function SmallStat({ label, value }: { label:string; value:string|number }) { return <div className="bg-[#050505] p-3"><p className="text-[8px] font-bold tracking-wider text-white/25">{label}</p><p className="mt-1 text-sm font-black">{value}</p></div>; }
function Funnel({ label, value, total }: { label:string; value:number; total:number }) { return <div><div className="mb-2 flex justify-between text-xs"><span className="text-white/50">{label}</span><span className="font-bold">{value} <span className="text-white/20">· {percent(value,total)}%</span></span></div><div className="h-2 bg-white/10"><div className="h-full customer-gradient" style={{width:`${total ? Math.max(2, Math.round(value/total*100)) : 0}%`}}/></div></div>; }
function Empty({ title, text }: { title:string; text:string }) { return <div className="p-12 text-center"><UserRound size={22} className="mx-auto text-white/20"/><h3 className="mt-4 font-black uppercase">{title}</h3><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-white/30">{text}</p></div>; }
function formatCurrency(value:number) { return `₹${Math.round(value).toLocaleString("en-IN")}`; }
function percent(value:number,total:number) { return total ? Math.round(value/total*100) : 0; }
function formatDate(value:string) { try { return new Date(value).toLocaleString("en-IN", {day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit"}); } catch { return "recently"; } }
