"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useRef, useState } from "react";
import { ArrowUpRight, BarChart3, Bot, BriefcaseBusiness, CheckSquare, ChevronRight, Command, ContactRound, LayoutDashboard, Megaphone, MessageSquare, Plus, Search, Sparkles, UsersRound, X } from "lucide-react";

const items = [
  ["Dashboard", "/protected", LayoutDashboard], ["Leads", "/leads", UsersRound], ["Pipeline", "/pipeline", BriefcaseBusiness], ["Customers", "/customers", ContactRound], ["Conversations", "/conversations", MessageSquare], ["Tasks", "/tasks", CheckSquare], ["AI Agents", "/ai-agents", Bot], ["Campaigns", "/campaigns", Megaphone], ["Analytics", "/analytics", BarChart3], ["Integrations", "/integrations", Command],
] as const;

export function WorkspaceShell({ title, eyebrow, children }: { title: string; eyebrow?: string; children: React.ReactNode }) {
  const pathname = usePathname(); const [query, setQuery] = useState(""); const [actionsOpen, setActionsOpen] = useState(false); const searchRef = useRef<HTMLInputElement>(null);
  const filtered = items.filter(([label]) => label.toLowerCase().includes(query.toLowerCase()));
  return <main className="leadflow-page"><div className="leadflow-shell px-4 sm:px-6 lg:px-10">
    <header className="leadflow-topline flex min-h-20 items-center justify-between gap-6"><Link href="/protected" className="group flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center bg-[#f4f0e7] text-sm font-black text-black transition group-hover:-translate-y-0.5">L</span><span className="text-sm font-black tracking-[.14em]">LEADFLOW</span><span className="hidden text-[9px] uppercase tracking-[.28em] text-white/35 sm:block">REVENUE OS / 01</span></Link><div className="flex items-center gap-2 sm:gap-4"><Link href="/auth/logout" className="hidden text-[10px] font-bold uppercase tracking-[.16em] text-white/45 transition hover:text-white sm:block">Sign out</Link><Link href="/ai-agents" className="hidden text-[10px] font-bold uppercase tracking-[.16em] text-white/45 transition hover:text-[#b7ff58] md:block">AI team</Link><Link href="/protected" className="leadflow-button leadflow-button-primary">Workspace <ArrowUpRight size={14}/></Link></div></header>
    <div className="flex gap-0 border-b border-white/10 lg:grid lg:min-h-[calc(100vh-80px)] lg:grid-cols-[230px_1fr]"><aside className="hidden border-r border-white/10 py-8 pr-6 lg:block"><p className="leadflow-kicker mb-5">Revenue desk</p><div className="mb-6 flex items-center gap-2 border border-white/10 bg-white/[.02] px-3 py-2"><Search size={14} className="text-white/35"/><input ref={searchRef} aria-label="Filter navigation" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Find a section" className="w-full bg-transparent text-xs outline-none placeholder:text-white/25"/>{query&&<button onClick={()=>setQuery("")} aria-label="Clear navigation search"><X size={13} className="text-white/25"/></button>}</div><nav className="space-y-1">{filtered.map(([label,href,Icon])=>{const active=pathname===href||(href!=="/protected"&&pathname.startsWith(href));return <Link key={href} href={href} aria-current={active?"page":undefined} data-active={active} className="workspace-nav-link flex items-center gap-3 px-3 py-3 text-xs font-semibold text-white/45"><Icon size={15}/><span>{label}</span>{label==="AI Agents"&&<span className="ml-auto text-[9px] text-[#b7ff58]">AI</span>}{active&&<ChevronRight size={13} className="ml-auto"/>}</Link>})}</nav><div className="mt-10 border-t border-white/10 pt-6"><Link href="/ai-agents" className="block border border-[#b7ff58]/25 bg-[#b7ff58]/[.05] p-4 text-left transition hover:border-[#b7ff58]/60"><div className="flex items-center gap-2 text-[#b7ff58]"><Sparkles size={14}/><span className="text-[10px] font-bold uppercase tracking-[.14em]">AI is working</span></div><p className="mt-2 text-[10px] leading-4 text-white/40">Open your agent team and see what each agent is responsible for.</p></Link></div></aside>
    <section className="min-w-0 flex-1 px-0 py-6 sm:py-8 lg:px-12"><nav className="mb-6 flex gap-1 overflow-x-auto border border-white/10 bg-[#080808] p-1 lg:hidden" aria-label="Workspace navigation">{items.map(([label,href,Icon])=>{const active=pathname===href||(href!=="/protected"&&pathname.startsWith(href));return <Link key={href} href={href} data-active={active} className="flex shrink-0 items-center gap-2 px-3 py-2.5 text-[10px] font-bold uppercase tracking-[.08em] text-white/40 data-[active=true]:bg-[#b7ff58]/10 data-[active=true]:text-[#b7ff58]"><Icon size={13}/>{label}</Link>})}</nav>
      <div className="mb-10 flex flex-col gap-5 border-b border-white/10 pb-8 md:flex-row md:items-end md:justify-between"><div>{eyebrow&&<p className="leadflow-kicker mb-3">{eyebrow}</p>}<h1 className="leadflow-title text-5xl sm:text-6xl lg:text-7xl">{title}</h1></div><div className="relative flex items-center gap-2"><button onClick={()=>searchRef.current?.focus()} className="leadflow-button"><Search size={14}/> Search</button><button onClick={()=>setActionsOpen(v=>!v)} aria-expanded={actionsOpen} className="leadflow-button leadflow-button-primary"><Plus size={14}/> New action</button>{actionsOpen&&<div className="absolute right-0 top-[52px] z-30 w-64 border border-white/15 bg-[#0a0a0a] p-2 shadow-2xl shadow-black/50"><p className="px-3 py-2 text-[9px] font-bold uppercase tracking-[.2em] text-white/25">Start something</p><ActionLink href="/leads/new" label="Add a new lead"/><ActionLink href="/tasks" label="Create a follow-up task"/><ActionLink href="/campaigns" label="Build a campaign"/><ActionLink href="/ai-agents" label="Configure an AI agent"/></div>}</div></div>{children}</section>
    </div>
  </div></main>;
}
function ActionLink({href,label}:{href:string;label:string}){return <Link href={href} onClick={()=>{}} className="flex items-center justify-between px-3 py-3 text-xs text-white/60 transition hover:bg-white/[.04] hover:text-[#b7ff58]">{label}<ArrowUpRight size={13}/></Link>}
