"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const fields = [
  ["enquiry","Enquiry","textarea"],["product_interest","Product / Service","input"],["budget_raw","Budget","input"],["location","Location","input"],["source","Source","input"],["campaign","Campaign","input"],["intent","Intent","input"],["category","Category","input"],["requirements","Requirements","textarea"],["timeline","Timeline","input"],["recommended_next_action","Recommended next action","textarea"],["deal_value","Deal value (₹)","input"]
] as const;

type Lead = Record<string, unknown>;
export default function LeadEditor({ lead }: { lead: Lead }) {
  const router = useRouter(); const [form,setForm]=useState<Record<string,string>>(() => Object.fromEntries(fields.map(([key]) => [key, lead[key] == null ? "" : String(lead[key])]))); const [stage,setStage]=useState(String(lead.stage || "NEW")); const [status,setStatus]=useState(String(lead.status || "OPEN")); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  function set(key:string,value:string){setForm(x=>({...x,[key]:value}))}
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError("");try{const res=await fetch("/api/leads/update",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:lead.id,...form,stage,status,deal_value:form.deal_value?Number(form.deal_value):null})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to save changes.");router.push(`/leads/${lead.id}`);router.refresh()}catch(err){setError(err instanceof Error?err.message:"Unable to save changes.");setSaving(false)}}
  return <form onSubmit={submit} className="mt-8 space-y-6"><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs text-white/45">Stage<select value={stage} onChange={e=>setStage(e.target.value)} className="mt-2 w-full border border-white/10 bg-white/[.03] p-3 text-sm text-white outline-none"><option>NEW</option><option>CONTACTED</option><option>QUALIFIED</option><option>PROPOSAL</option><option>WON</option><option>LOST</option></select></label><label className="text-xs text-white/45">Status<select value={status} onChange={e=>setStatus(e.target.value)} className="mt-2 w-full border border-white/10 bg-white/[.03] p-3 text-sm text-white outline-none"><option>OPEN</option><option>ACTIVE</option><option>WON</option><option>LOST</option><option>CLOSED</option></select></label></div><div className="grid gap-4 md:grid-cols-2">{fields.map(([key,label,type])=><label key={key} className={type==="textarea"?"text-xs text-white/45 md:col-span-2":"text-xs text-white/45"}>{label}{type==="textarea"?<textarea rows={4} value={form[key]} onChange={e=>set(key,e.target.value)} className="mt-2 w-full resize-y border border-white/10 bg-white/[.03] p-3 text-sm text-white outline-none focus:border-[#b7ff58]/50"/>:<input value={form[key]} onChange={e=>set(key,e.target.value)} className="mt-2 w-full border border-white/10 bg-white/[.03] p-3 text-sm text-white outline-none focus:border-[#b7ff58]/50"/>}</label>)}</div>{error&&<div className="border border-red-400/30 bg-red-400/5 p-4 text-sm text-red-300">{error}</div>}<div className="flex gap-3 border-t border-white/10 pt-6"><button disabled={saving} className="bg-[#b7ff58] px-6 py-3 text-xs font-black uppercase tracking-[.14em] text-black disabled:opacity-50">{saving?"Saving…":"Save changes"}</button><button type="button" onClick={()=>router.back()} className="border border-white/10 px-6 py-3 text-xs font-bold uppercase tracking-[.14em] text-white/55 hover:text-white">Cancel</button></div></form>;
}
